# This rule is not used by the project trustee-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to trusteeconfig resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: trustee-operator
    app.kubernetes.io/managed-by: kustomize
  name: trusteeconfig-viewer-role
rules:
- apiGroups:
  - trustee.confidentialcontainers.org
  resources:
  - trusteeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trustee.confidentialcontainers.org
  resources:
  - trusteeconfigs/status
  verbs:
  - get
